version: "3"
services:
  database:
    image: "postgres"
    environment:
      - POSTGRES_USER=localdev
      - POSTGRES_PASSWORD=localdev_password
      - POSTGRES_DB=approved_premises_localdev
    volumes:
      - database-data-development:/var/lib/postgresql/data/
    ports:
      - "5432:5432"

volumes:
  database-data-development:
