version: "3"
services:
  integration_test_database:
    image: "postgres"
    environment:
      - POSTGRES_USER=integration_test
      - POSTGRES_PASSWORD=integration_test_password
      - POSTGRES_DB=approved_premises_integration_test
    ports:
      - "5433:5432"
