swagger: "2.0"
info:
  title: "Approved Premises ('mini-manage' stubs)"
  version: "1.0.0"
paths:
  /premises:
    get:
      summary: "Lists all approved premises"
      responses:
        "200":
          description: "successful operation"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/Premises"
        "401":
          description: "not authenticated"
        "403":
          description: "unauthorised"
        "500":
          description: "unexpected error"

  /premises/{premisesID}:
    get:
      summary: "Returns an approved premises"
      parameters:
        - name: "premisesID"
          in: "path"
          description: "ID of the premises to return"
          required: true
          type: "integer"
          format: "uuid"
      responses:
        "200":
          description: "successful operation"
          schema:
            $ref: "#/definitions/Premises"
        "401":
          description: "not authenticated"
        "403":
          description: "unauthorised"
        "404":
          description: "invalid premises ID"
        "500":
          description: "unexpected error"
  /premises/{premisesID}/residents:
    get:
      summary: "Returns all the residents in an approved premise with the given ID"
      parameters:
        - name: "premisesID"
          in: "path"
          description: "ID of the premises to get residents for"
          required: true
          type: "integer"
          format: "uuid"
      responses:
        "200":
          description: "successful operation"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/Person"
        "401":
          description: "not authenticated"
        "403":
          description: "unauthorised"
        "404":
          description: "invalid premises ID"
        "500":
          description: "unexpected error"

  /premises/{premisesID}/bookings:
    get:
      summary: "Returns all bookings for an approved premises"
      parameters:
        - name: "premisesID"
          in: "path"
          description: "ID of the premises to get bookings for"
          required: true
          type: "integer"
          format: "uuid"
      responses:
        "200":
          description: "successful operation"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/Booking"
        "401":
          description: "not authenticated"
        "403":
          description: "unauthorised"
        "404":
          description: "invalid premises ID"
        "500":
          description: "unexpected error"
    post:
      summary: "Adds a new booking for an approved premises"
      parameters:
        - name: "premisesID"
          in: "path"
          description: "ID of the premises to get bookings for"
          required: true
          type: "integer"
          format: "uuid"
        - name: "body"
          in: "body"
          required: false
          schema:
            $ref: "#/definitions/Booking"
      responses:
        "200":
          description: "successful operation"
          schema:
            $ref: "#/definitions/Booking"
        "400":
          description: "invalid params"
        "401":
          description: "not authenticated"
        "403":
          description: "unauthorised"
        "404":
          description: "invalid premises ID"
        "500":
          description: "unexpected error"

  /premises/{premisesID}/bookings/{bookingID}/arrivals:
    post:
      summary: "Posts an arrival to a specified approved premise booking"
      parameters:
        - name: "premisesID"
          in: "path"
          description: "ID of the premises the booking is related to"
          required: true
          type: "integer"
          format: "uuid"
        - name: "bookingID"
          in: "path"
          description: "ID of the booking"
          required: true
          type: "integer"
          format: "uuid"
        - in: "body"
          name: "body"
          description: "details of the arrival"
          required: true
          schema:
            $ref: "#/definitions/Arrival"
      responses:
        "200":
          description: "successful operation"
          schema:
            $ref: "#/definitions/Arrival"
        "400":
          description: "invalid params"
        "401":
          description: "not authenticated"
        "403":
          description: "unauthorised"
        "404":
          description: "invalid premisesID or bookingID"
        "500":
          description: "unexpected error"

  /premises/{premisesID}/bookings/{bookingID}/departure:
    post:
      summary: "Posts a departure to a specified approved premise booking"
      parameters:
        - name: "premisesID"
          in: "path"
          description: "ID of the premises the booking is related to"
          required: true
          type: "integer"
          format: "uuid"
        - name: "bookingID"
          in: "path"
          description: "ID of the booking"
          required: true
          type: "integer"
          format: "uuid"
        - in: "body"
          name: "body"
          description: "details of the departure"
          required: true
          schema:
            $ref: "#/definitions/Departure"
      responses:
        "200":
          description: "successful operation"
          schema:
            $ref: "#/definitions/Departure"
        "400":
          description: "invalid params"
        "401":
          description: "not authenticated"
        "403":
          description: "unauthorised"
        "404":
          description: "invalid premisesID or bookingID"
        "500":
          description: "unexpected error"

  /premises/{premisesID}/bookings/{bookingID}/non-arrival:
    post:
      summary: "Posts an non-arrival to a specified approved premise booking"
      parameters:
        - name: "premisesID"
          in: "path"
          description: "ID of the premises the booking is related to"
          required: true
          type: "integer"
          format: "uuid"
        - name: "bookingID"
          in: "path"
          description: "ID of the booking"
          required: true
          type: "integer"
          format: "uuid"
        - in: "body"
          name: "body"
          description: "details of the non-arrival"
          required: true
          schema:
            $ref: "#/definitions/Nonarrival"
      responses:
        "200":
          description: "successful operation"
          schema:
            $ref: "#/definitions/Nonarrival"
        "400":
          description: "invalid params"
        "401":
          description: "not authenticated"
        "403":
          description: "unauthorised"
        "404":
          description: "invalid premisesID or bookingID"
        "500":
          description: "unexpected error"

  /premises/{premisesID}/bookings/{bookingID}/lost-beds:
    post:
      summary: "Posts a lost bed to a specified approved premise booking"
      parameters:
        - name: "premisesID"
          in: "path"
          description: "ID of the premises the booking is related to"
          required: true
          type: "integer"
          format: "uuid"
        - name: "bookingID"
          in: "path"
          description: "ID of the booking"
          required: true
          type: "integer"
          format: "uuid"
        - name: "body"
          in: "body"
          description: "details of the lost bed"
          required: true
          schema:
            $ref: "#/definitions/LostBed"
      responses:
        "200":
          description: "successful operation"
          schema:
            $ref: "#/definitions/LostBed"
        "400":
          description: "invalid params"
        "401":
          description: "not authenticated"
        "403":
          description: "unauthorised"
        "404":
          description: "invalid premisesID or bookingID"
        "500":
          description: "unexpected error"

definitions:
  Premises:
    type: "object"
    properties:
      id:
        type: "string"
        format: "uuid"
      name:
        type: "string"
      apCode:
        type: "string"
      probationRegionId:
        type: "string"
      postcode:
        type: "string"
      bedCount:
        type: "integer"
      apAreaId:
        type: "string"
      localAuthorityArea:
        type: "string"
  Booking:
    type: "object"
    properties:
      id:
        type: "string"
        format: "uuid"
      CRN:
        type: "string"
      arrivalDate:
        type: "string"
        format: "date"
      departureDate:
        type: "string"
        format: "date"
      keyWorker:
        type: "string"
  Person:
    type: "object"
    properties:
      CRN:
        type: "string"
      name:
        type: "string"
  Arrival:
    type: "object"
    properties:
      bookingID:
        type: "string"
        format: "uuid"
      dateTime:
        type: "string"
        format: "date"
      expectedDepartureDate:
        type: "string"
        format: "date"
      notes:
        type: "string"
  Nonarrival:
    type: "object"
    properties:
      bookingID:
        type: "string"
        format: "uuid"
      date:
        type: "string"
        format: "date"
      reason:
        type: "string"
      notes:
        type: "string"
  Departure:
    type: "object"
    properties:
      bookingID:
        type: "string"
        format: "uuid"
      dateTime:
        type: "string"
        format: "date"
      reason:
        type: "string"
        enum:
          - "Absconded"
          - "Planned move"
          - "Recalled"
      notes:
        type: "string"
      moveOnCategory:
        type: "string"
        enum:
          - "Private house"
          - "Custody"
          - "Deported"
      destinationProvider:
        type: "string"
        enum:
          - "Example destination provider"
  LostBed:
    type: "object"
    properties:
      startDate:
        type: "string"
        format: "date"
      endDate:
        type: "string"
        format: "date"
      numberOfBeds:
        type: "integer"
      reason:
        type: "string"
        enum:
          - "Fire"
          - "Damaged"
          - "refurbishment"
          - "Staff shortage"
      referenceNumber:
        type: "string"
        format: "uuid"
      notes:
        type: "string"