openapi: 3.0.1
info:
  title: Approved Premises ('mini-manage' stubs)
  version: 1.0.0
servers:
- url: /
paths:
  /premises:
    get:
      summary: Lists all approved premises
      responses:
        200:
          description: successful operation
          content:
            'application/json':
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Premises'
        401:
          description: not authenticated
          content: {}
        403:
          description: unauthorised
          content: {}
        500:
          description: unexpected error
          content: {}
  /premises/{premisesId}:
    get:
      summary: Returns an approved premises
      parameters:
      - name: premisesId
        in: path
        description: ID of the premises to return
        required: true
        schema:
          type: integer
          format: uuid
      responses:
        200:
          description: successful operation
          content:
            'application/json':
              schema:
                $ref: '#/components/schemas/Premises'
        401:
          description: not authenticated
          content: {}
        403:
          description: unauthorised
          content: {}
        404:
          description: invalid premises ID
          content: {}
        500:
          description: unexpected error
          content: {}
  /premises/{premisesId}/residents:
    get:
      summary: Returns all the residents in an approved premises with the given ID
      parameters:
      - name: premisesId
        in: path
        description: ID of the premises to get residents for
        required: true
        schema:
          type: integer
          format: uuid
      responses:
        200:
          description: successful operation
          content:
            'application/json':
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Person'
        401:
          description: not authenticated
          content: {}
        403:
          description: unauthorised
          content: {}
        404:
          description: invalid premises ID
          content: {}
        500:
          description: unexpected error
          content: {}
  /premises/{premisesId}/bookings:
    get:
      summary: Returns all bookings for an approved premises
      parameters:
      - name: premisesId
        in: path
        description: ID of the premises to get bookings for
        required: true
        schema:
          type: integer
          format: uuid
      responses:
        200:
          description: successful operation
          content:
            'application/json':
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Booking'
        401:
          description: not authenticated
          content: {}
        403:
          description: unauthorised
          content: {}
        404:
          description: invalid premises ID
          content: {}
        500:
          description: unexpected error
          content: {}
    post:
      summary: Adds a new booking for an approved premises
      parameters:
      - name: premisesId
        in: path
        description: ID of the premises to get bookings for
        required: true
        schema:
          type: integer
          format: uuid
      requestBody:
        content:
          'application/json':
            schema:
              $ref: '#/components/schemas/NewBooking'
        required: false
      responses:
        200:
          description: successful operation
          content:
            'application/json':
              schema:
                $ref: '#/components/schemas/Booking'
        400:
          description: invalid params
          content:
            'application/problem+json':
              schema:
                $ref: '#/components/schemas/ValidationError'
        401:
          description: not authenticated
          content: {}
        403:
          description: unauthorised
          content: {}
        404:
          description: invalid premises ID
          content: {}
        500:
          description: unexpected error
          content: {}
      x-codegen-request-body-name: body
  /premises/{premisesId}/bookings/{bookingId}/arrivals:
    post:
      summary: Posts an arrival to a specified approved premises booking
      parameters:
      - name: premisesId
        in: path
        description: ID of the premises the booking is related to
        required: true
        schema:
          type: integer
          format: uuid
      - name: bookingId
        in: path
        description: ID of the booking
        required: true
        schema:
          type: integer
          format: uuid
      requestBody:
        description: details of the arrival
        content:
          'application/json':
            schema:
              $ref: '#/components/schemas/Arrival'
        required: true
      responses:
        200:
          description: successful operation
          content:
            'application/json':
              schema:
                $ref: '#/components/schemas/Arrival'
        400:
          description: invalid params
          content:
            'application/problem+json':
              schema:
                $ref: '#/components/schemas/ValidationError'
        401:
          description: not authenticated
          content: {}
        403:
          description: unauthorised
          content: {}
        404:
          description: invalid premisesId or bookingId
          content: {}
        500:
          description: unexpected error
          content: {}
      x-codegen-request-body-name: body
  /premises/{premisesId}/bookings/{bookingId}/departures:
    post:
      summary: Posts a departure to a specified approved premises booking
      parameters:
      - name: premisesId
        in: path
        description: ID of the premises the booking is related to
        required: true
        schema:
          type: integer
          format: uuid
      - name: bookingId
        in: path
        description: ID of the booking
        required: true
        schema:
          type: integer
          format: uuid
      requestBody:
        description: details of the departure
        content:
          'application/json':
            schema:
              $ref: '#/components/schemas/Departure'
        required: true
      responses:
        200:
          description: successful operation
          content:
            'application/json':
              schema:
                $ref: '#/components/schemas/Departure'
        400:
          description: invalid params
          content:
            'application/problem+json':
              schema:
                $ref: '#/components/schemas/ValidationError'
        401:
          description: not authenticated
          content: {}
        403:
          description: unauthorised
          content: {}
        404:
          description: invalid premisesId or bookingId
          content: {}
        500:
          description: unexpected error
          content: {}
      x-codegen-request-body-name: body
  /premises/{premisesId}/bookings/{bookingId}/non-arrivals:
    post:
      summary: Posts an non-arrival to a specified approved premises booking
      parameters:
      - name: premisesId
        in: path
        description: ID of the premises the booking is related to
        required: true
        schema:
          type: integer
          format: uuid
      - name: bookingId
        in: path
        description: ID of the booking
        required: true
        schema:
          type: integer
          format: uuid
      requestBody:
        description: details of the non-arrival
        content:
          'application/json':
            schema:
              $ref: '#/components/schemas/Nonarrival'
        required: true
      responses:
        200:
          description: successful operation
          content:
            'application/json':
              schema:
                $ref: '#/components/schemas/Nonarrival'
        400:
          description: invalid params
          content:
            'application/problem+json':
              schema:
                $ref: '#/components/schemas/ValidationError'
        401:
          description: not authenticated
          content: {}
        403:
          description: unauthorised
          content: {}
        404:
          description: invalid premisesId or bookingId
          content: {}
        500:
          description: unexpected error
          content: {}
      x-codegen-request-body-name: body
  /premises/{premisesId}/bookings/{bookingId}/lost-beds:
    post:
      summary: Posts a lost bed to a specified approved premises booking
      parameters:
      - name: premisesId
        in: path
        description: ID of the premises the booking is related to
        required: true
        schema:
          type: integer
          format: uuid
      - name: bookingId
        in: path
        description: ID of the booking
        required: true
        schema:
          type: integer
          format: uuid
      requestBody:
        description: details of the lost bed
        content:
          'application/json':
            schema:
              $ref: '#/components/schemas/LostBed'
        required: true
      responses:
        200:
          description: successful operation
          content:
            'application/json':
              schema:
                $ref: '#/components/schemas/LostBed'
        400:
          description: invalid params
          content:
            'application/problem+json':
              schema:
                $ref: '#/components/schemas/ValidationError'
        401:
          description: not authenticated
          content: {}
        403:
          description: unauthorised
          content: {}
        404:
          description: invalid premisesId or bookingId
          content: {}
        500:
          description: unexpected error
          content: {}
      x-codegen-request-body-name: body
components:
  schemas:
    Premises:
      type: object
      properties:
        id:
          type: string
          format: uuid
        name:
          type: string
          example: Hope House
        apCode:
          type: string
          example: NEHOPE1
        postcode:
          type: string
          example: LS1 3AD
        bedCount:
          type: integer
          example: 22
        probationRegion:
          $ref: '#/components/schemas/ProbationRegion'
        apArea:
          $ref: '#/components/schemas/ApArea'
        localAuthorityArea:
          $ref: '#/components/schemas/LocalAuthorityArea'
    LocalAuthorityArea:
      type: object
      properties:
        id:
          type: string
          example: LEEDS
        name:
          type: string
          example: Leeds City Council
    ApArea:
      type: object
      properties:
        id:
          type: string
          example: 1500001234
        name:
          type: string
          example: Yorkshire & The Humber
    ProbationRegion:
      type: object
      properties:
        id:
          type: string
          example: 1500123456
        name:
          type: string
          example: NPS North East Central Referrals
    BookingBody:
      type: object
      properties:
        id:
          type: string
          format: uuid
        person: 
          $ref: '#/components/schemas/Person'
        arrivalDate:
          type: string
          format: date
        departureDate:
          type: string
          format: date
        keyWorker:
          type: string
    NewBooking:
      type: object
      properties:
        crn:
          type: string
          example: A123456
        expectedArrivalDate:
          type: string
          format: date
          example: 2022-07-28
        expectedDepartureDate:
          type: string
          format: date
          example: 2022-09-30
        apCode:
          type: string
          example: NELEH
        keyWorkerId:
          type: string
    Booking:
      allOf:
        - $ref: '#/components/schemas/BookingBody'
        - type: object
          properties:
            status:
              type: string
              enum:
              - arrived
              - awaiting-arrival
              - not-arrived
              - departed
              - cancelled
            arrival:
              nullable: true
              allOf:
                - $ref: '#/components/schemas/Arrival'
            departure:
              nullable: true
              allOf:
                - $ref: '#/components/schemas/Departure'
            nonArrival:
              nullable: true
              allOf:
                - $ref: '#/components/schemas/Nonarrival'
            cancellation:
              nullable: true
              allOf:
              - $ref: '#/components/schemas/Cancellation'
    Person:
      type: object
      properties:
        crn:
          type: string
        name:
          type: string
    Arrival:
      type: object
      properties:
        bookingId:
          type: string
          format: uuid
        person: 
          $ref: '#/components/schemas/Person'
        arrivalDate:
          type: string
          format: date
        expectedDepartureDate:
          type: string
          format: date
        notes:
          type: string
    Nonarrival:
      type: object
      properties:
        bookingId:
          type: string
          format: uuid
        date:
          type: string
          format: date
        reason:
          type: string
        notes:
          type: string
    Cancellation:
      type: object
      properties:
        bookingId:
          type: string
          format: uuid
        date:
          type: string
          format: date
        reason:
          type: string
        notes:
          type: string
    Departure:
      type: object
      properties:
        bookingId:
          type: string
          format: uuid
        dateTime:
          type: string
          format: date
        reason:
          type: string
          enum:
          - Absconded
          - Planned move
          - Recalled
        notes:
          type: string
        moveOnCategory:
          type: string
          enum:
          - Private house
          - Custody
          - Deported
        destinationProvider:
          type: string
          enum:
          - Example destination provider
    ValidationError:
      type: object
      properties:
        type:
          type: string
          example: https://example.net/validation-error
        title:
          type: string
          example: Invalid request parameters
        code:
          type: number
          example: 400.0
        invalid-params:
          type: array
          items:
            $ref: '#/components/schemas/InvalidParam'
    InvalidParam:
      type: object
      properties:
        propertyName:
          type: string
          example: arrivalDate
        errorType:
          type: string
          enum:
          - blank
          - invalid
          - mustBePast
          - mustBeFuture
    LostBed:
      type: object
      properties:
        startDate:
          type: string
          format: date
        endDate:
          type: string
          format: date
        numberOfBeds:
          type: integer
        reason:
          type: string
          enum:
          - Fire
          - Damaged
          - refurbishment
          - Staff shortage
        referenceNumber:
          type: string
          format: uuid
        notes:
          type: string
